quarkus.quinoa.ui-dir=src/main/webui
quarkus.quinoa.dev-server.port=5175
quarkus.http.port=8080
quarkus.quinoa.ignored-path-prefixes=/api
quarkus.package.type=uber-jar
quarkus.quinoa.enable-spa-routing=true
quarkus.banner.path=banner.txt


